Cinema/Cinema/Models/Tickets/Genre.cs
namespace Cinema.Models.Tickets
{
    public enum Genre
    {
        Comedy,
        Horror,
        Family,
        Action
    }
}

Cinema/Cinema/Models/Tickets/Hall.cs
namespace Cinema.Models.Tickets
{
    public class Hall
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Cinema/Cinema/Models/Tickets/HallInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cinema.Models.Tickets
{
    public class HallInfo
    {
        public Tariff CurrentTariff { get; set; }
        public int CurrentTimeslotId { get; set; }
        public TimeSlotSeatRequest[] RequestedSeats { get; set; }
    }
}

Cinema/Cinema/Models/Tickets/Movie.cs
namespace Cinema.Models.Tickets
{
    public class Movie
    {
        public int Id { get; set; } // todo Guid
        public string Name { get; set; }
        public string Description { get; set; }
        public int MinAge { get; set; }
        public int Duration { get; set; }
        public float Rating { get; set; }
        public Type[] Types { get; set; }
        public Genre[] Genres { get; set; }
        public string ImageUrl { get; set; }
    }
}

Cinema/Cinema/Models/Tickets/MovieListItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cinema.Models.Tickets
{
    public class MovieListItem
    {
        public Movie Movie { get; set; }
        public TimeSlotTag[] AvailableTimeSlots { get; set; }
    }
}

Cinema/Cinema/Models/Tickets/RequestStatus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cinema.Models.Tickets
{
    public enum RequestStatus
    {
        Buy,
        Reserve
    }
}

Cinema/Cinema/Models/Tickets/SeatsProcessRequests.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cinema.Models.Tickets
{
    public class SeatsProcessRequests
    {
        public int TimeSlotId { get; set; }

        public SeatsRequest SeatsRequest { get; set; }

        public RequestStatus SelectedStatus { get; set; }
    }
}

Cinema/Cinema/Models/Tickets/SeatsRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cinema.Models.Tickets
{
    public class SeatsRequest
    {
        public SelectedSeat[] AddedSeats { get; set; }
        public decimal Sum { get; set; }
    }
}

Cinema/Cinema/Models/Tickets/SelectedSeat.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cinema.Models.Tickets
{
    public class SelectedSeat
    {
        public int Row { get; set; }
        public int Seat { get; set; }
    }
}

Cinema/Cinema/Models/Tickets/SubNavigationMenu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cinema.Models.Tickets
{
    public enum SubNavigationMenu
    {
        Movies,
        TimeSlots,
        Tariffs,
        Halls
    }
}

Cinema/Cinema/Models/Tickets/Tariff.cs
namespace Cinema.Models.Tickets
{
    public class Tariff
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
    }
}

Cinema/Cinema/Models/Tickets/TicketsJsonModel.cs
namespace Cinema.Models.Tickets
{
    public class TicketsJsonModel
    {
        public Movie[] Movies { get; set; }
        public Hall[] Halls { get; set; }
        public TimeSlot[] TimeSlots { get; set; }
        public Tariff[] Tariffs { get; set; }
    }
}

Cinema/Cinema/Models/Tickets/TimeSlot.cs
using System;

namespace Cinema.Models.Tickets
{
    public class TimeSlot
    {
        public int Id { get; set; }
        public DateTime StartTime { get; set; }
        public int MovieId { get; set; }
        public int HallId { get; set; }
        public int TariffId { get; set; }
        public TimeSlotSeatRequest[] RequestedSeats { get;  set; }
    }
}

Cinema/Cinema/Models/Tickets/TimeSlotGridRow.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cinema.Models.Tickets
{
    public class TimeSlotGridRow
    {
        public int Id { get; set; }
        public DateTime StartTime { get; set; }
        public string MovieName { get; set; }
        public string HallName { get; set; }
        public string TariffName { get; set; }
    }
}

Cinema/Cinema/Models/Tickets/TimeSlotSeatRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cinema.Models.Tickets
{
    public class TimeSlotSeatRequest
    {
        public int Row { get; set; }
        public int Seat { get; set; }
        public RequestStatus Status { get; set; }

    }
}

Cinema/Cinema/Models/Tickets/TimeSlotTag.cs
using System;

namespace Cinema.Models.Tickets
{
    public class TimeSlotTag
    {
        public int TimeSlotId { get; set; }
        public DateTime StartTime { get; set; }
        public decimal Cost { get; set; }

    }
}

Cinema/Cinema/Models/Tickets/Type.cs
namespace Cinema.Models.Tickets
{
    public enum Type
    {
        D2,
        D3
    }
}

Cinema/Cinema/Controllers/TicketsController.cs
using Cinema.Attributes;
using Cinema.Models.Tickets;
using Cinema.Services;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Type = Cinema.Models.Tickets.Type;


namespace Cinema.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ITicketService _ticketService;

        public TicketsController(ITicketService ticketService)
        {
            _ticketService = ticketService;
        }

        public ActionResult GetMovies()
        {
            var allMovies = _ticketService.GetFullMoviesInfo();
            return View("~/Views/Tickets/MoviesList.cshtml", allMovies);
        }

        public ActionResult GetHallInfo(int timeSlotId)
        {
            //return null;

            var timeSlot = _ticketService.GetTimeSlotById(timeSlotId);
            var currentTariff = _ticketService.GetTariffById(timeSlot.TariffId);
            var model = new HallInfo
            {
                CurrentTariff = currentTariff,
                CurrentTimeslotId = timeSlotId,
                RequestedSeats = timeSlot.RequestedSeats
            };
            return View("~/Views/Tickets/HallInfo.cshtml", model);
        }

        public string ProcessRequest(SeatsProcessRequests request)
        {
            var requestProcessingResult = _ticketService.AddRequestedSeatsToTimeSlot(request);
            return JsonConvert.SerializeObject(new
            {
                requestResult = requestProcessingResult
            });
        }
    }
}

Cinema/Cinema/Views/Tickets/HallInfo.cshtml
@model Cinema.Models.Tickets.HallInfo
@{
    var rows = 12;
    var columns = 20;
}

@functions
{
    string CheckSeatClass(int row, int seat)
    {
        var matchingSeat = Model.RequestedSeats?.FirstOrDefault(x => x.Row == row && x.Seat == seat);
        if (matchingSeat == null)
            return string.Empty;

        return matchingSeat.Status == Cinema.Models.Tickets.RequestStatus.Buy ? "is-sold" : "is-reserved";
    }

    string CheckSeatAvailability(int row, int seat)/*запрет на выбор уже зарезервированного*/
    {
        var matchingSeat = Model.RequestedSeats?.FirstOrDefault(x => x.Row == row && x.Seat == seat);
        if (matchingSeat == null)
            return string.Empty;

        return "disabled";
    }

}

<h1>Select your seat</h1>
<div class="row js-seat-container"
     data-current-cost="@Model.CurrentTariff.Cost.ToString("####")"
     data-current-timeslot-id="@Model.CurrentTimeslotId">
    <div class="col-md-10">
        @for (int i = 1; i <= rows; i++)
        {
            <div class="cinema-row">
                <div class="cinema-row-label">Row @i</div>
                @for (int j = 1; j <= columns; j++)
                {
                    <div class="cinema-seat @CheckSeatClass(i,j)">
                        <input class="seat-input js-seat-selector"
                               type="checkbox"
                               id="check-row@(i)-col@(j)"
                               data-seat-row="@i"
                               data-seat-col="@j"
                               @CheckSeatAvailability(i, j) />
                        <label class="seat-label" for="check-row@(i)-col@(j)">@j</label>
                    </div>
                }
            </div>
        }
    </div>
    <div class="col-md-2">
        Selected seats:
        <div class="js-seat-result-container">
        </div>
        <div class="btn btn-default btn-block js-reserve-seats">Make a reservation</div>
        <div class="btn btn-success btn-block js-buy-seats">Buy tickets</div>
    </div>
</div>



<div class="js-selected-seat-template hidden">
    {{#each addedSeats}}
    <div>
        Row{{row}}, Seat{{seat}}
    </div>
    {{/each}}
    {{#if addedSeats}}
    <div>
        Total:{{sum}}
    </div>
    {{/if}}
</div>

@*<div class="entry-template">
        <div class="entry">
            <h1>{{title}} Row {{row}}</h1>
        </div>
    </div>*@

Cinema/Cinema/Views/Tickets/MoviesList.cshtml
@using Cinema.Extensions
@model Cinema.Models.Tickets.MovieListItem[]

@foreach (var movieItem in Model)
{
    <div class="movie-list-section">
        <div class="row">
            <div class="col-md-3 movie-list-header">
                <div class="name-movie-list">@movieItem.Movie.Name</div>
                <div class="rating-movies-list">@movieItem.Movie.Rating</div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <div>
                    <img class="img-rounded img-movies-list" src="@movieItem.Movie.ImageUrl" />
                </div>
                <div class="movie-list-footer">
                    <div class="genres-movie-list">
                        <div>
                            @string.Join(", ", movieItem.Movie.Genres)
                        </div>
                        <div>
                            @movieItem.Movie.Duration.ToDuration()
                        </div>
                    </div>
                    <div class="age-movies-list">
                        @movieItem.Movie.MinAge+
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                @foreach (var timeSlotTag in movieItem.AvailableTimeSlots)
                {
                    <div class="timeslot-tag">
                        @Html.ActionLink(timeSlotTag.StartTime.ToShortTimeString(), "GetHallInfo", "Tickets", new { timeSlotId = timeSlotTag.TimeSlotId }, new { @class = "btn btn-default btn-block" })

                        @timeSlotTag.StartTime
                        @*<span>@string.Format("{0}P", timeSlotTag.Cost)</span>*@
                        <span>@timeSlotTag.Cost.ToString("####") P</span>
                    </div>
                }
            </div>
        </div>

    </div>
}