Cinema/Cinema/Controllers/TicketsAdminController.cs
using Cinema.Attributes;
using Cinema.Models.Tickets;
using Cinema.Services;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Type = Cinema.Models.Tickets.Type;


namespace Cinema.Controllers
{
    public class TicketsAdminController : Controller
    {
        private readonly ITicketService _ticketService;

        public TicketsAdminController(ITicketService ticketService)
        {
            _ticketService = ticketService;
        }


        public ActionResult GetMoviesList()
        {
            var movies = _ticketService.GetAllMovies();
            return View("~/Views/TicketsAdmin/MovieList.cshtml", movies);
        }

        [HttpGet]
        public ActionResult AddMovie()
        {
            return View("~/Views/TicketsAdmin/AddMovie.cshtml");
        }

        [HttpPost]
        public ActionResult AddMovie(Movie newMovie)
        {
            var createResult = _ticketService.CreateMovie(newMovie);
            if (createResult)
                return RedirectToAction("GetMoviesList");

            return Content("Update failed, please contact administaration");
        }

        [HttpGet]
        public ActionResult EditMovie(int movieId)
        {
            var movie = _ticketService.GetMovieById(movieId);
            return View("~/Views/TicketsAdmin/EditMovie.cshtml", movie);
        }

        [HttpPost]
        public ActionResult EditMovie(Movie updatedMovie)
        {
            var updateResult = _ticketService.UpdateMovie(updatedMovie);
            if (updateResult)
                return RedirectToAction("GetMoviesList");

            return Content("Update failed, please contact administaration");
        }


        public ActionResult RemoveMovie(int movieId)
        {
            var removeResult = _ticketService.RemoveMovie(movieId);
            if (removeResult)
                return RedirectToAction("GetMoviesList");

            return Content("Update failed, please contact administaration");
        }

        public ActionResult GetHallsList()
        {
            var halls = _ticketService.GetAllHalls();
            return View("~/Views/TicketsAdmin/HallList.cshtml", halls);
        }

        [HttpGet]
        public ActionResult EditHall(int hallId)
        {
            var hall = _ticketService.GetHallById(hallId);
            return View("~/Views/TicketsAdmin/EditHall.cshtml", hall);
        }

        [HttpPost]
        public ActionResult EditHall(Hall updatedHall)
        {
            var updateResult = _ticketService.UpdateHall(updatedHall);
            if (updateResult)
                return RedirectToAction("GetHallsList");

            return Content("Update failed, please contact administaration");
        }

        public ActionResult GetTariffsList()
        {
            var tariff = _ticketService.GetAllTariffs();
            return View("~/Views/TicketsAdmin/TariffList.cshtml", tariff);
        }

        [HttpGet]
        public ActionResult EditTariff(int tariffId)
        {
            var tariff = _ticketService.GetTariffById(tariffId);
            return View("~/Views/TicketsAdmin/EditTariff.cshtml", tariff);
        }

        [HttpPost]
        public ActionResult EditTariff(Tariff updatedTariff)
        {
            var updateResult = _ticketService.UpdateTariff(updatedTariff);
            if (updateResult)
                return RedirectToAction("GetTariffsList");

            return Content("Update failed, please contact administaration");
        }



        public ActionResult GetTimeSlotsList()
        {
            var timeSlots = _ticketService.GetAllTimeSlots();
            var resultModel = ProcessTimeSLot(timeSlots);
            return View("~/Views/TicketsAdmin/TimeSlotList.cshtml", resultModel);
        }


        public ActionResult GetMovieTimeSlotsList(int timeSlotId)
        {
            var timeSlots = _ticketService.GetTimeSlotsByMovieId(timeSlotId);
            var resultModel = ProcessTimeSLot(timeSlots);
            return View("~/Views/TicketsAdmin/TimeSlotList.cshtml", resultModel);
        }


        private TimeSlotGridRow[] ProcessTimeSLot(TimeSlot[] timeSlots)
        {
            var movies = _ticketService.GetAllMovies();
            var halls = _ticketService.GetAllHalls();
            var tariffs = _ticketService.GetAllTariffs();

            var resultModels = new List<TimeSlotGridRow>();
            foreach (var timeSlot in timeSlots)
            {
                resultModels.Add(new TimeSlotGridRow
                {
                    Id = timeSlot.Id,
                    StartTime = timeSlot.StartTime,
                    MovieName = movies.FirstOrDefault(movie => movie.Id == timeSlot.MovieId)?.Name ?? "Data Not Found",
                    HallName = halls.FirstOrDefault(hall => hall.Id == timeSlot.HallId)?.Name ?? "Data Not Found",
                    TariffName = tariffs.FirstOrDefault(tariff => tariff.Id == timeSlot.TariffId)?.Name ?? "Data Not Found"
                });
            }

            return resultModels.ToArray();
        }

        [HttpGet]
        [PopulateMoviesList, PopulateHallsList, PopulateTariffsList]
        public ActionResult AddTimeSlot()
        {
            return View("~/Views/TicketsAdmin/AddTimeSlot.cshtml");
        }

        [HttpPost]
        public ActionResult AddTimeSlot(TimeSlot addTimeSlot)
        {
            var addResult = _ticketService.CreateTimeSlot(addTimeSlot);
            if (addResult)
                return RedirectToAction("GetTimeSlotsList");

            return Content("Update failed, please contact administaration");
        }


        [HttpGet]
        [PopulateMoviesList, PopulateHallsList, PopulateTariffsList]
        public ActionResult EditTimeSlot(int timeSlotId)
        {
            var timeSlot = _ticketService.GetTimeSlotById(timeSlotId);
            return View("~/Views/TicketsAdmin/EditTimeSlot.cshtml", timeSlot);
        }

        [HttpPost]
        public ActionResult EditTimeSlot(TimeSlot updatedTimeSlot)
        {
            var updateResult = _ticketService.UpdateTimeSlot(updatedTimeSlot);
            if (updateResult)
                return RedirectToAction("GetTimeSlotsList");

            return Content("Update failed, please contact administaration");
        }

        public ActionResult FindMovieById(int id)
        {
            var movie = _ticketService.GetMovieById(id);
            if (movie == null)
                return Content("Movie with such Id do not exist");

            var modelJson = JsonConvert.SerializeObject(movie);
            return Content(modelJson, "application/json");
        }

        public ActionResult FindAllMovies()
        {
            var movie = _ticketService.GetAllMovies();
            if (movie == null)
                return Content("Movies do not exist");

            var modelJson = JsonConvert.SerializeObject(movie);
            return Content(modelJson, "application/json");
        }

        public ActionResult FindHallById(int id)
        {
            var hall = _ticketService.GetHallById(id);
            if (hall == null)
                return Content("Hall with such Id do not exist");

            var modelJson = JsonConvert.SerializeObject(hall);
            return Content(modelJson, "application/json");
        }

        public ActionResult FindAllHalls()
        {
            var hall = _ticketService.GetAllHalls();
            if (hall == null)
                return Content("Halls do not exist");

            var modelJson = JsonConvert.SerializeObject(hall);
            return Content(modelJson, "application/json");
        }

        public ActionResult FindTimeSlotById(int id)
        {
            var timeSlot = _ticketService.GetTimeSlotById(id);
            if (timeSlot == null)
                return Content("TimeSlot with such Id do not exist");

            var modelJson = JsonConvert.SerializeObject(timeSlot);
            return Content(modelJson, "application/json");
        }

        public ActionResult FindAllTimeSlots()
        {
            var timeSlot = _ticketService.GetAllTimeSlots();
            if (timeSlot == null)
                return Content("TimeSlots do not exist");

            var modelJson = JsonConvert.SerializeObject(timeSlot);
            return Content(modelJson, "application/json");
        }

        public ActionResult FindTariffById(int id)
        {
            var tariff = _ticketService.GetTariffById(id);
            if (tariff == null)
                return Content("Tariff with such Id do not exist");

            var modelJson = JsonConvert.SerializeObject(tariff);
            return Content(modelJson, "application/json");
        }

        public ActionResult FindAllTariffs()
        {
            var tariff = _ticketService.GetAllTariffs();
            if (tariff == null)
                return Content("Tariffs do not exist");

            var modelJson = JsonConvert.SerializeObject(tariff);
            return Content(modelJson, "application/json");
        }


        #region old
        //private readonly string PathToJson = "/Bd/Tickets.json";

        //public ActionResult SaveTickets()
        //{
        //    var movies = new Movie[]
        //        {
        //          new Movie
        //          {
        //             Id=1,
        //             Name= "Дэдпул 2",

Cinema/Cinema/Views/TicketsAdmin/AddMovie.cshtml
@using Cinema.Models.Tickets
@model Cinema.Models.Tickets.Movie

@section SubNav
{
    @Html.Partial("~/Views/Shared/SubNavigation.cshtml", SubNavigationMenu.Movies)
}

<h2>Add Movie</h2>

@using (Html.BeginForm("AddMovie", "TicketsAdmin"))
{
    <div class="form-group">
        @Html.LabelFor(x => x.Name)
        @Html.EditorFor(x => x.Name, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.ImageUrl)
        @Html.EditorFor(x => x.ImageUrl, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Description)
        @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Duration)
        @Html.EditorFor(x => x.Duration, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.MinAge)
        @Html.EditorFor(x => x.MinAge, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Rating)
        @Html.EditorFor(x => x.Rating, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>

    @Html.Partial("~/Views/Editors/Types.cshtml")
    @Html.Partial("~/Views/Editors/Genre.cshtml")
    <input type="submit" value="Add changes" class="btn btn-success"/>
}

Cinema/Cinema/Views/TicketsAdmin/AddTimeSlot.cshtml
@using Cinema.Models.Tickets
@model Cinema.Models.Tickets.TimeSlot

@section SubNav
{
    @Html.Partial("~/Views/Shared/SubNavigation.cshtml", SubNavigationMenu.TimeSlots)
}

<h2>TimeSlots Add</h2>
@using (Html.BeginForm("AddTimeSlot", "TicketsAdmin"))
{
    <div class="form-group">
        @Html.LabelFor(x => x.StartTime)
        <div class='input-group date' id='@Html.IdFor(x=>x.StartTime)'>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
            <input type='text' name="@Html.NameFor(x=>x.StartTime)" class="form-control" />
        </div>
    </div>

    @Html.Partial("~/Views/Editors/MoviesList.cshtml")
    @Html.Partial("~/Views/Editors/HallsList.cshtml")
    @Html.Partial("~/Views/Editors/TariffsList.cshtml")

    <input type="submit" value="Add timeslot" class="btn btn-success" />
}

@section scripts
    {
    <script type="text/javascript">
         $(function () {
             $('#@Html.IdFor(x=>x.StartTime)').datetimepicker({
                 format: 'DD.MM.YYYY hh:mm:ss',
                 locale: 'ru'
             });
         });
    </script>
}

Cinema/Cinema/Views/TicketsAdmin/EditHall.cshtml
@using Cinema.Models.Tickets
@model Cinema.Models.Tickets.Hall

@section SubNav
{
    @Html.Partial("~/Views/Shared/SubNavigation.cshtml", SubNavigationMenu.Halls)
}

<h2>Halls Edit</h2>
@using (Html.BeginForm("EditHall", "TicketsAdmin"))
{
    @Html.HiddenFor(x => x.Id)
    <div class="form-group">
        @Html.LabelFor(x => x.Name)
        @Html.EditorFor(x => x.Name, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>

    <input type="submit" value="Save changes" class="btn btn-success" />
}

Cinema/Cinema/Views/TicketsAdmin/EditMovie.cshtml
@using Cinema.Models.Tickets
@model Cinema.Models.Tickets.Movie

@section SubNav
{
    @Html.Partial("~/Views/Shared/SubNavigation.cshtml", SubNavigationMenu.Movies)
}

<h2>Edit Movie</h2>
@using (Html.BeginForm("EditMovie", "TicketsAdmin"))
{
    @Html.HiddenFor(x => x.Id)
    <div class="form-group">
        @Html.LabelFor(x => x.Name)
        @Html.EditorFor(x => x.Name, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.ImageUrl)
        @Html.EditorFor(x => x.ImageUrl, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Description)
        @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Duration)
        @Html.EditorFor(x => x.Duration, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.MinAge)
        @Html.EditorFor(x => x.MinAge, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Rating)
        @Html.EditorFor(x => x.Rating, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>

    @Html.Partial("~/Views/Editors/Types.cshtml", Model.Types)
    @Html.Partial("~/Views/Editors/Genre.cshtml", Model.Genres)
    <input type="submit" value="Save changes" class="btn btn-success"/>
}

Cinema/Cinema/Views/TicketsAdmin/EditTariff.cshtml
@using Cinema.Models.Tickets
@model Cinema.Models.Tickets.Tariff

@section SubNav
{
    @Html.Partial("~/Views/Shared/SubNavigation.cshtml", SubNavigationMenu.Tariffs)
}

<h2>Tariffs Edit</h2>
@using (Html.BeginForm("EditTariff", "TicketsAdmin"))
{
    @Html.HiddenFor(x => x.Id)
    <div class="form-group">
        @Html.LabelFor(x => x.Name)
        @Html.EditorFor(x => x.Name, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Cost)
        @Html.EditorFor(x => x.Cost, new { htmlAttrubutes = new { @class = "form-control" } })
    </div>
    <input type="submit" value="Save changes" class="btn btn-success" />
}

Cinema/Cinema/Views/TicketsAdmin/EditTimeSlot.cshtml
@using Cinema.Models.Tickets
@model Cinema.Models.Tickets.TimeSlot

@section SubNav
{
    @Html.Partial("~/Views/Shared/SubNavigation.cshtml", SubNavigationMenu.TimeSlots)
}

<h2>TimeSlots Edit</h2>
@using (Html.BeginForm("EditTimeSlot", "TicketsAdmin"))
{
    @Html.HiddenFor(x => x.Id)
    <div class="form-group">
        <div class="form-group">
            @Html.LabelFor(x => x.StartTime)
            <div class='input-group date' id='@Html.IdFor(x=>x.StartTime)'>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
                <input type='text' name="@Html.NameFor(x=>x.StartTime)" class="form-control" value="@Model.StartTime" />
            </div>
        </div>
    </div>

    @Html.Partial("~/Views/Editors/MoviesList.cshtml", Model.MovieId)
    @Html.Partial("~/Views/Editors/HallsList.cshtml", Model.HallId)
    @Html.Partial("~/Views/Editors/TariffsList.cshtml", Model.TariffId)

    <input type="submit" value="Save changes" class="btn btn-success" />
}

@section scripts
    {
    <script type="text/javascript">
         $(function () {
             $('#@Html.IdFor(x=>x.StartTime)').datetimepicker({
                 format: 'DD.MM.YYYY hh:mm:ss',
                 locale: 'ru'
             });
         });
    </script>
}

Cinema/Cinema/Views/TicketsAdmin/GetMovieTimeSlotsList.cshtml
@using Cinema.Models.Tickets

@model TimeSlotGridRow[]

@section SubNav
{
    @Html.Partial("~/Views/Shared/SubNavigation.cshtml", SubNavigationMenu.TimeSlots)
}
<h2 class="admin-heading">TimeSlots List</h2>

<div class="admin-add-btn">
    @Html.ActionLink("Add timeSlot", "AddTimeSlot", "TicketsAdmin", null, new { @class = "btn btn-success btn-block" })
</div>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th style="min-width: 50px">id</th>
            <th style="min-width: 50px">Start Time</th>
            <th style="min-width: 100px">Movie</th>
            <th style="min-width: 100px">Hall</th>
            <th style="min-width: 100px">Tariff</th>
            <th style="min-width: 100px">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var timeSlot in Model)
        {
            <tr>
                <td>@timeSlot.Id</td>
                <td>@timeSlot.StartTime</td>
                <td>@timeSlot.MovieName</td>
                <td>@timeSlot.HallName</td>
                <td>@timeSlot.TariffName</td>
                <td>@Html.ActionLink("Edit", "EditTimeSlot", "TicketsAdmin", new { timeSlotId = timeSlot.Id }, new { @class = "btn btn-primary btn-block" })</td>
            </tr>
        }
    </tbody>
</table>

Cinema/Cinema/Views/TicketsAdmin/HallList.cshtml
@using Cinema.Models.Tickets
@model Cinema.Models.Tickets.Hall[]

@section SubNav
{
    @Html.Partial("~/Views/Shared/SubNavigation.cshtml", SubNavigationMenu.Halls)
}

    <h2>Halls List</h2>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var hall in Model)
        {
            <tr>
                <td>@hall.Id</td>
                <td>@hall.Name</td>
                <td>@Html.ActionLink("Edit", "EditHall", "TicketsAdmin", new { hallId = hall.Id }, new { @class = "btn btn-primary btn-block" })</td>
            </tr>
        }
    </tbody>
</table>

Cinema/Cinema/Views/TicketsAdmin/MovieList.cshtml
@using Cinema.Models.Tickets
@model Cinema.Models.Tickets.Movie[]

@section SubNav
{
    @Html.Partial("~/Views/Shared/SubNavigation.cshtml", SubNavigationMenu.Movies)
}
<h2 class="admin-heading">Movies List</h2>
<div class="admin-add-btn">
    @Html.ActionLink("Add movie", "AddMovie", "TicketsAdmin", null, new { @class = "btn btn-success btn-block" })
</div>


<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th class="col">id</th>
            <th class="col">Poster</th>
            <th class="col">Name</th>
            <th class="col">Description</th>
            <th class="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var movie in Model)
        {
            <tr>
                <td>@movie.Id</td>
                <td><img style="max-height: 100px" src="@movie.ImageUrl" /></td>
                <td>@movie.Name</td>
                <td>@movie.Description</td>
                <td class="col-lg-2">
                    @Html.ActionLink("Edit", "EditMovie", "TicketsAdmin", new { movieId = movie.Id }, new { @class = "btn btn-primary btn-block" })
                    @Html.ActionLink("TimeSlots", "GetMovieTimeSlotsList", "TicketsAdmin", new { timeSlotId = movie.Id }, new { @class = "btn btn-primary btn-block" })
                    @Html.ActionLink("Delete", "RemoveMovie", "TicketsAdmin", new { movieId = movie.Id }, new { @class = "btn btn-danger btn-block" })
                </td>
            </tr>
        }
    </tbody>
</table>

Cinema/Cinema/Views/TicketsAdmin/TariffList.cshtml
@using Cinema.Models.Tickets
@model Cinema.Models.Tickets.Tariff[]

@section SubNav
{
    @Html.Partial("~/Views/Shared/SubNavigation.cshtml", SubNavigationMenu.Tariffs)
}

<h2>Tariffs List</h2>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>Cost</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var tariff in Model)
        {
            <tr>
                <td>@tariff.Id</td>
                <td>@tariff.Name</td>
                <td>@tariff.Cost</td>
                <td>@Html.ActionLink("Edit", "EditTariff", "TicketsAdmin", new { tariffId = tariff.Id }, new { @class = "btn btn-primary btn-block" })</td>
            </tr>
        }
    </tbody>
</table>

Cinema/Cinema/Views/TicketsAdmin/TimeSlotList.cshtml
@using Cinema.Models.Tickets

@model TimeSlotGridRow[]

@section SubNav
{
    @Html.Partial("~/Views/Shared/SubNavigation.cshtml", SubNavigationMenu.TimeSlots)
}
    <h2 class="admin-heading">TimeSlots List</h2>

    <div class="admin-add-btn">
        @Html.ActionLink("Add timeSlot", "AddTimeSlot", "TicketsAdmin", null, new { @class = "btn btn-success btn-block" })
    </div>

<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th style="min-width: 50px">id</th>
            <th style="min-width: 50px">Start Time</th>
            <th style="min-width: 100px">Movie</th>
            <th style="min-width: 100px">Hall</th>
            <th style="min-width: 100px">Tariff</th>
            <th style="min-width: 100px">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var timeSlot in Model)
        {
            <tr>
                <td>@timeSlot.Id</td>
                <td>@timeSlot.StartTime</td>
                <td>@timeSlot.MovieName</td>
                <td>@timeSlot.HallName</td>
                <td>@timeSlot.TariffName</td>
                <td>@Html.ActionLink("Edit", "EditTimeSlot", "TicketsAdmin", new { timeSlotId = timeSlot.Id }, new { @class = "btn btn-primary btn-block" })</td>
            </tr>
        }
    </tbody>
</table>